# Generated by hand to ensure the quotes table exists for demos
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [django.db.models.expressions.F('likes').desc()],
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('text','source'), name='unique_text_source'),
        ),
    ]
